# Generated by Django 2.0.13 on 2019-10-02 08:16

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('dss_pharos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='EconomicSector',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='activity',
            new_name='economic_sector',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='activity',
            new_name='economic_sector',
        ),
    ]
