# Generated by Django 2.2.6 on 2019-10-03 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dss_pharos', '0003_auto_20191002_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_name', models.TextField(max_length=100)),
                ('economic_sector', models.ManyToManyField(to='dss_pharos.EconomicSector')),
                ('user_type', models.ManyToManyField(to='dss_pharos.UserType')),
            ],
            options={
                'ordering': ['impact_name'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='economic_sector',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='condition',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dss_pharos.UserType'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='collection',
            name='impact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dss_pharos.Impact'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='impact',
            field=models.ManyToManyField(through='dss_pharos.Collection', to='dss_pharos.Impact'),
        ),
    ]
