# Generated by Django 2.2.6 on 2019-10-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss_pharos', '0005_auto_20191003_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impact',
            name='all_users',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='all_users',
            field=models.BooleanField(default=False),
        ),
    ]
