# Generated by Django 2.2.6 on 2019-10-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dss_pharos', '0006_auto_20191003_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impact',
            name='user_type',
        ),
    ]
