# Generated by Django 2.2.6 on 2019-11-02 19:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss_pharos', '0008_usertype_economic_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textView', models.CharField(max_length=100)),
                ('textContent', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
