# Generated by Django 2.2.6 on 2019-11-02 19:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss_pharos', '0009_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicsector',
            name='form_enabled',
            field=models.BooleanField(default=True, verbose_name='This sector has form enabled'),
        ),
        migrations.AlterField(
            model_name='economicsector',
            name='bg_information',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Background infromations'),
        ),
        migrations.AlterField(
            model_name='economicsector',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='economicsector',
            name='interactions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Impacts/Interactions '),
        ),
        migrations.AlterField(
            model_name='economicsector',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='impact',
            name='impact_name',
            field=models.CharField(max_length=100, verbose_name='Impact name'),
        ),
    ]
